### ISSUE TITLE
Planetside 2 now working

### ISSUE THREAD

**Issue by HarmonBlues** [aclist/aclist.github.io#11]
Battleye is now working with Planetside 2 under "Proton Battleye Runtime" in Steam.

**Comment by aclist** [comment]
Thanks for the note. I believe some games are essentially working now with this change, but not all are "sanctioned," so to speak. Have Valve or the Planetside 2 devs announced this? The only ones I've seen expressly listed in patch notes are ARK and Mount & Blade II.

**Comment by aclist** [comment]
Updated in [368e02c152357a31c57ca0814c8b6763c8c52586](https://github.com/aclist/aclist.github.io/commit/368e02c152357a31c57ca0814c8b6763c8c52586)
