### ISSUE TITLE
Hired Ops

### ISSUE THREAD

**Issue by againstalllog1c** [aclist/aclist.github.io#12]
Free online shooter set in Tarkov. Runs out the box with Proton via Steam. In-house anticheat, works perfectly.

**Comment by aclist** [comment]
Thank you, it seems to be server-side/authoritative with some manual review. Will add it. Is this game fun?

**Comment by aclist** [comment]
https://aclist.github.io/#hiredops

**Comment by Faalagorn** [comment]
This anticheat is called Sabreclaw anticheat and has been used in other Russia 2028 universe games, Contract Wars uses it and I think it was what Tarkov used before BattlEye? Great additions anyway!

**Comment by aclist** [comment]
Thanks, updated that detail.
