### ISSUE TITLE
Hell Let Loose - official Steam Deck support planned

### ISSUE THREAD

**Issue by Florian7843** [aclist/aclist.github.io#17]
https://www.youtube.com/watch?t=386&v=DJqh61nfuTs&feature=youtu.be

**Comment by aclist** [comment]
Thank you for the report. Updated here: https://aclist.github.io/#hll

This update also includes changes to:

- Day of Infamy
- Dead by Daylight
- Fall Guys
- Hunt Showdown
- Insurgency Sandstorm
- The Finals

**Comment by Florian7843** [comment]
Hell Let Loose is now working. I don't know about a official statement, but have been able to play. 

https://www.protondb.com/app/686810

**Comment by aclist** [comment]
@Florian7843  Thank you for the update and apologies for the slow response. This is official, as it was previously announced to gain Steam Deck support in September 2023. I have updated the entry for HLL accordingly: https://aclist.github.io/#hll.
