### ISSUE TITLE
Add anchors

### ISSUE THREAD

**Issue by aclist** [aclist/aclist.github.io#6]

**Comment by NoXPhasma** [comment]
Anchors do not work, no matter if I use chromium or firefox, nothing happens when I click on them. Why do you even use javascript for that purpose? Just add a proper in site link:

```html
<a class="sharelink" id="7daysnative" href="#7daysnative">-§-</a>
```

**Comment by aclist** [comment]
It's working here. It copies the anchor text to your clipboard on click so that you can "share" it by pasting it. Does that not work for you? I assumed most people find it uncomfortable to right click -> copy link for direct links and would rather click once.

**Comment by aclist** [comment]
I see what you were saying now. So you would rather have it be a normal anchor, which updates the window location, and then the user copies it out of their URL bar. I guess that is more in keeping with expected behavior. I think either of these methods is suitable. I just made it a one-click thing in order to reduce the workload on the user, but if it's confusing, then it's not ideal. There's actually a button next to the code snippet you posted on this page that you can click and it creates a "Copied!" tooltip. Maybe something like that, but it seems a bit overkill as well. I don't really know what users prefer, just want clarity and simplicity.

**Comment by NoXPhasma** [comment]
I'm fine with it being a copy function, if the user gets notified. Not only as for convenience, but also to make it clear to the user that the clipboard has changed. I don't want to sound over dramatic, but changing the clipboard is something also malicious sites do. So having the user notified about that, is definitely a good thing.

I also noticed that you have a text in the top explaining it will copy it to the clipboard, by I totally ignored that, which leads to my confusion.

**Comment by aclist** [comment]
Updated it, tell me if this is better.

**Comment by aclist** [comment]
Sure, thanks.
